//Back-end API URL
export const ENDPOINT = 'http://localhost:5000/'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SPREADSHEETS_LOAD_SUCCESS = 'SPREADSHEETS_LOAD_SUCCESS'
export const SPREADSHEETS_LOAD_FAILED = 'SPREADSHEETS_LOAD_FAILED'
export const SPREADSHEETS_KEYS_LOAD_SUCCESS = 'SPREADSHEETS_KEYS_LOAD_SUCCESS'
export const SPREADSHEETS_KEYS_LOAD_FAILED = 'SPREADSHEETS_KEYS_LOAD_FAILED'
export const SPREADSHEETS_KEYS_CLEAR = 'SPREADSHEETS_KEYS_CLEAR'
export const SPREADSHEETS_TABLES_LOAD_SUCCESS = 'SPREADSHEETS_TABLES_LOAD_SUCCESS'
export const SPREADSHEETS_TABLES_LOAD_FAILED = 'SPREADSHEETS_TABLES_LOAD_FAILED'
export const SPREADSHEETS_TABLES_CLEAR = 'SPREADSHEETS_TABLES_CLEAR'
export const DEDUPLICATION_SUCCESS = 'DEDUPLICATION_SUCCESS'
export const DEDUPLICATION_FAILED = 'DEDUPLICATION_FAILED'






